# Generated by Django 5.2.4 on 2026-05-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtransaction',
            name='category',
        ),
    ]
